[build]
  functions = "functions"

[functions]
  node_bundler = "esbuild"

# Optional: Add headers for your API functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    
[[scheduled]]
path = "/fetch-issues"
schedule = "@hourly"
