name: GitGlyph CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
            
      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 4: Run unit tests
      - name: Run tests
        run: go test ./...

      # Step 5: Lint code
      - name: Lint code
        run: golangci-lint run
