name: Fetch Issues and Send Notifications

on:
  schedule:
    # Runs the workflow every 2 hours
<<<<<<< HEAD
    - cron: "0 */2 * * *"
=======
    - cron: "*/5 * * * *"
>>>>>>> 68545c03193d45aa9bdcc36b38e07f6f0f6ee36a

  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  fetch-issues:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 4: Run the Go application
      - name: Fetch Issues and Send Notifications
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }} # Token for GitHub GraphQL API
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }} # Email account username
          WPRD_MAIL: ${{ secrets.WPRD_MAIL }} # Email account app password
          SMTP_SERVER: "smtp.gmail.com"                # Change for your email provider
          SMTP_PORT: "587"                             # SMTP Port
<<<<<<< HEAD
          REPO_OWNER: "kubevirt"                       # Replace with target repo owner
          REPO_NAME: "kubevirt"                        # Replace with target repo name
          LABEL: "good-first-issue"                    # Replace with the desired label
          RECEIVER_EMAIL: "receiver@example.com"       # Replace with recipient email
=======
          REPO_OWNER: "Dharma-09"                       # Replace with target repo owner
          REPO_NAME: "CI-CD-pipelines-examples"                        # Replace with target repo name
          LABEL: "good-first-issue"                    # Replace with the desired label
          RECEIVER_EMAIL: "dharmik.gangani17@gmail.com"       # Replace with recipient email
>>>>>>> 68545c03193d45aa9bdcc36b38e07f6f0f6ee36a
        run: |
          go run main.go
